# SPF 网络拓扑配置文件
# 使用方法: bin/spf_route -config configs/topology.toml -node nodeA

[[nodes]]
id = "nodeA"
ip = "127.0.0.1"
grpc_port = 5001
serf_port = 7001
# join 为空表示第一个节点，作为集群入口

[[nodes]]
id = "nodeB"
ip = "127.0.0.1"
grpc_port = 5002
serf_port = 7002
join = "127.0.0.1:7001"

[[nodes]]
id = "nodeC"
ip = "127.0.0.1"
grpc_port = 5003
serf_port = 7003
join = "127.0.0.1:7001"

[[nodes]]
id = "nodeD"
ip = "127.0.0.1"
grpc_port = 5004
serf_port = 7004
join = "127.0.0.1:7001"

[[nodes]]
id = "nodeE"
ip = "127.0.0.1"
grpc_port = 5005
serf_port = 7005
join = "127.0.0.1:7001"

# 边配置 (无向图)
# 每条边定义两个节点之间的连接和成本
# [[edges]]
# from = "nodeA"
# to = "nodeB"
# cost = 1

# [[edges]]
# from = "nodeA"
# to = "nodeC"
# cost = 2

# [[edges]]
# from = "nodeB"
# to = "nodeC"
# cost = 1

# [[edges]]
# from = "nodeB"
# to = "nodeD"
# cost = 3

# [[edges]]
# from = "nodeC"
# to = "nodeD"
# cost = 1

# [[edges]]
# from = "nodeC"
# to = "nodeE"
# cost = 2

# [[edges]]
# from = "nodeD"
# to = "nodeE"
# cost = 1
